# Site settings
title: Lawrence Chang
email: lawrencium.chang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  © 2015 Lawrence Chang
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: lawrenciumchang	
github_username:  lawrenciumchang

# Build settings
markdown: kramdown
